var express = require('express');
var app = express();
var bodyparser = require('body-parser');
const server = require('http').createServer(app);
var io = require('socket.io').listen(server);
var path = require('path');
var fs = require('fs');
var util = require('util');
var last_modified = new Date(2000, 12, 24, 10, 33, 30, 0);

let i = 0;


var logText = 'New file logs started: \r\n';

app.use(bodyparser.urlencoded({ extended: false }));
app.use(bodyparser.json());

function writelog(){
    if (logText) {
        fs.appendFile('log.txt', logText, (err) => {
            if (err) throw err;
            logText = 'log generated'+ i +'\r\n';
            i++;
        });
    }
}

function writelog2(){
    if (logText) {
        fs.appendFile('log.txt', logText, (err) => {
            if (err) throw err;
            logText = 'log generated by function 2:::'+ i +'\r\n';
            i++;
        });
    }
}

io.on('connection', function(socket)  { 
  socket.on('disconnect', function () {
    io.emit('user disconnected');
  });

  var watcher = fs.watch('log.txt', function(){
  //  console.log('The file has just changed.');

      fs.stat("log.txt", function(err, stats){
          var mtime = new Date(util.inspect(stats.mtime));

          if(mtime>last_modified){
               fs.readFile("log.txt", "utf8", function(error, data) {
                  var theFile = data.toString().split("\n");
                  var requiredData = theFile.slice(-11);
                  socket.emit('logs', { logs: requiredData });
               });
          } 
      }); 
    });
  });



const port =3000;

app.use(express.static(path.join(__dirname,'public')));

app.get('/',(req,res)=>{
	res.sendFile(__dirname + '/client/index.html');
  setInterval(writelog, 5000);
  setInterval(writelog2, 10000);
})

server.listen(port,()=>{
console.log('server1 is at port '+port);
})